spring.application.name=password-manager


#########################################
# DATABASE
#########################################
spring.datasource.url=jdbc:postgresql://localhost:5432/name-database


spring.datasource.username=name
spring.datasource.password=password


#######################
## myBatis
#######################
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.milanzaric.password_manager.model
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
mybatis.type-handlers-package=com.milanzaric.password_manager.config